// CCMM 점심 룰렛 후보 데이터 (index.html 이 읽음)
// src   : 비고(휴무일·참고 점수 등). 화면에 그대로 표시된다.
// zone  : META.zones 의 id. inScope:false 인 구역은 기본으로 룰렛에서 빠진다.
// closed: true 로 두면 목록에는 남고 룰렛에서만 빠진다.
window.META = {
  "zones": [
    {
      "id": "ccmm",
      "label": "CCMM빌딩 안"
    },
    {
      "id": "bank",
      "label": "은행로 (중기중앙회·정우/안원빌딩)"
    },
    {
      "id": "alley",
      "label": "국회대로 62~76길 골목 (순복음교회 뒤)"
    },
    {
      "id": "main",
      "label": "국회대로 본선 (LG에클라트·금산빌딩·파라곤)"
    },
    {
      "id": "station",
      "label": "국회의사당역 3~6번 출구 (익스콘·더샵아일랜드파크)"
    },
    {
      "id": "west",
      "label": "국회 경내·KBS",
      "inScope": false
    }
  ],
  "footer": "범위: 여의도공원 서측(여의공원로 기준) ~ 국회의사당역 출구 앞. 국회 경내·KBS는 기본 제외. 카카오맵 조회(2026-09-28) 기준이며 술집·치킨 배달집·구내식당·1인 2만 원 초과 확인 식당은 뺐습니다. 비고에 '확인 필요'가 있는 곳은 폐점·가격을 확인해 주세요. 목록 수정은 data.js."
};

window.RESTAURANTS = [
  // ── CCMM빌딩 안
  {"id": "hemil", "name": "헤밀파스타", "cat": "양식", "menu": "파스타·리조또 (샐러드·식전빵 제공)", "price": "", "addr": "여의공원로 101 B106호", "bldg": "CCMM빌딩 지하 아케이드", "zone": "ccmm", "src": "토 휴무", "q": ""},
  {"id": "gaya", "name": "가야분식", "cat": "분식·기타", "menu": "분식", "price": "", "addr": "여의공원로 101 지하1층", "bldg": "CCMM빌딩 지하 아케이드", "zone": "ccmm", "src": "", "q": ""},
  {"id": "kisoya", "name": "기소야 서여의도점", "cat": "일식", "menu": "냄비돈까스정식·김치우동", "price": "1.2만~1.6만", "addr": "여의공원로 101 지하1층", "bldg": "CCMM빌딩 지하 아케이드", "zone": "ccmm", "src": "토 휴무", "q": "", "franchise": true},
  {"id": "ttukbaegi", "name": "여의도뚝배기", "cat": "한식", "menu": "뚝배기 정식", "price": "", "addr": "여의공원로 101 지하1층", "bldg": "CCMM빌딩 지하 아케이드", "zone": "ccmm", "src": "", "q": ""},
  // ── 은행로 (중기중앙회·정우/안원빌딩)
  {"id": "k-동해도일식본점", "name": "동해도일식 본점", "cat": "일식", "menu": "일식", "price": "", "addr": "은행로 25", "bldg": "안원빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-프라임한우", "name": "프라임한우", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "은행로 25", "bldg": "안원빌딩", "zone": "bank", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-5징어", "name": "5징어", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-고려삼계탕", "name": "고려삼계탕", "cat": "한식", "menu": "삼계탕", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-김가네김밥여의도2호점", "name": "김가네김밥 여의도2호점", "cat": "분식·기타", "menu": "김가네", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-도시해장국본점", "name": "도시해장국 본점", "cat": "한식", "menu": "해장국", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-도시해장국여의도점2호", "name": "도시해장국 여의도점 2호", "cat": "한식", "menu": "해장국", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "dwipuri", "name": "뒤풀이", "cat": "한식", "menu": "반건조 대구 해장국", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-바다내음", "name": "바다내음", "cat": "한식", "menu": "회", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-삼형제김밥여의도점", "name": "삼형제김밥 여의도점", "cat": "분식·기타", "menu": "삼형제김밥", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-상상", "name": "상상", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-서울뚝배기", "name": "서울뚝배기", "cat": "한식", "menu": "한식", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-스시야", "name": "스시야", "cat": "일식", "menu": "초밥,롤", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-써니즉석떡볶이", "name": "써니즉석떡볶이", "cat": "분식·기타", "menu": "떡볶이", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-에브리데이샐러드", "name": "에브리데이샐러드", "cat": "분식·기타", "menu": "샐러드", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-여심식당", "name": "여심식당", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-여의도돈가스백반여의도본점", "name": "여의도돈가스백반 여의도본점", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-오로지라멘서여의도점", "name": "오로지라멘 서여의도점", "cat": "일식", "menu": "일본식라면", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-원조삼계탕", "name": "원조삼계탕", "cat": "한식", "menu": "삼계탕", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-원중쌀국수여의도본점", "name": "원중쌀국수 여의도본점", "cat": "아시안", "menu": "베트남음식", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-이든돈카츠", "name": "이든돈카츠", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-장타이펑", "name": "장타이펑", "cat": "중식", "menu": "중국요리", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "k-질할브로스여의도점", "name": "질할브로스 여의도점", "cat": "양식", "menu": "양식", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-카츠미야비", "name": "카츠미야비", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-해바라기", "name": "해바라기", "cat": "한식", "menu": "삼겹살", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "jungwoo", "name": "정우칼국수보쌈", "cat": "한식", "menu": "칼국수·보쌈", "price": "", "addr": "은행로 29 지하1층", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "haru", "name": "하루순대국밥", "cat": "한식", "menu": "순대국밥·밀면", "price": "", "addr": "은행로 29 지하1층 50호", "bldg": "정우빌딩", "zone": "bank", "src": "일 휴무", "q": ""},
  {"id": "sanjeong", "name": "산정", "cat": "한식", "menu": "한식 정식", "price": "", "addr": "은행로 29 지하1층 56호", "bldg": "정우빌딩", "zone": "bank", "src": "주말 휴무 · 카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-남도마루여의도동점", "name": "남도마루 여의도동점", "cat": "한식", "menu": "회", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-느루", "name": "느루", "cat": "한식", "menu": "한식", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": ""},
  {"id": "k-서촌닭갈비여의도점", "name": "서촌닭갈비 여의도점", "cat": "한식", "menu": "닭요리", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-엄마손감자탕", "name": "엄마손감자탕", "cat": "한식", "menu": "감자탕", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-천지명", "name": "천지명", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": ""},
  {"id": "k-하동관국회의사당역직영점", "name": "하동관 국회의사당역직영점", "cat": "한식", "menu": "곰탕", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "bulls", "name": "불스버거", "cat": "양식", "menu": "수제버거 (B.T.D·클래식치즈)", "price": "1만~1.2만", "addr": "은행로 3 지하1층 B113호", "bldg": "익스콘벤처타워", "zone": "bank", "src": "3번 출구 앞", "q": "", "franchise": true},
  {"id": "k-달맞이꽃게탕서여의도점", "name": "달맞이꽃게탕 서여의도점", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "은행로 30", "bldg": "중소기업중앙회", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-메밀나무여의도점", "name": "메밀나무 여의도점", "cat": "한식", "menu": "국수", "price": "", "addr": "은행로 30", "bldg": "중소기업중앙회", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-피오레", "name": "피오레", "cat": "양식", "menu": "양식", "price": "", "addr": "은행로 30", "bldg": "중소기업중앙회", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-해담채여의도점", "name": "해담채 여의도점", "cat": "한식", "menu": "한정식", "price": "", "addr": "은행로 30", "bldg": "중소기업중앙회", "zone": "bank", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "bonavetti", "name": "보나베띠 여의도점", "cat": "양식", "menu": "화덕피자·파스타", "price": "", "addr": "은행로 30 1층", "bldg": "중소기업중앙회 신관", "zone": "bank", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-판동면옥여의도점", "name": "판동면옥 여의도점", "cat": "한식", "menu": "냉면", "price": "", "addr": "은행로 37", "bldg": "한국기계산업진흥회(기계회관)", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "k-팔당반점서여의도점", "name": "팔당반점 서여의도점", "cat": "중식", "menu": "중국요리", "price": "", "addr": "은행로 37", "bldg": "한국기계산업진흥회(기계회관)", "zone": "bank", "src": "", "q": "", "franchise": true},
  // ── 국회대로 62~76길 골목 (순복음교회 뒤)
  {"id": "k-중화식당다복", "name": "중화식당 다복", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로62길 11", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-화제의국밥", "name": "화제의국밥", "cat": "한식", "menu": "국밥", "price": "", "addr": "국회대로62길 14", "bldg": "한국스카우트연맹빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "bongtaemin", "name": "봉태민 여의도점", "cat": "한식", "menu": "요일 백반 (닭볶음 메인)", "price": "9천", "addr": "국회대로62길 14 지하1층", "bldg": "한국스카우트연맹빌딩", "zone": "alley", "src": "다이닝코드 47점", "q": ""},
  {"id": "jeongdong", "name": "정동각", "cat": "중식", "menu": "짜장·짬뽕·볶음밥 (지하, 반주 가능)", "price": "5천~7천 (구정보)", "addr": "국회대로62길 14 지하1층", "bldg": "한국스카우트연맹빌딩", "zone": "alley", "src": "다이닝코드 31점", "q": ""},
  {"id": "k-비봉", "name": "비봉", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 15", "bldg": "광복회관", "zone": "alley", "src": "", "q": ""},
  {"id": "k-제이레스토랑", "name": "제이레스토랑", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로62길 15", "bldg": "광복회관", "zone": "alley", "src": "", "q": ""},
  {"id": "k-화해당여의도점", "name": "화해당 여의도점", "cat": "한식", "menu": "게,대게", "price": "", "addr": "국회대로62길 15", "bldg": "광복회관", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-이가우육면", "name": "이가우육면", "cat": "중식", "menu": "중식", "price": "", "addr": "국회대로62길 21", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-후루룩2호점", "name": "후루룩 2호점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 21", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-구름산추어탕서여의도점", "name": "구름산추어탕 서여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-김춘자의정부부대찌개", "name": "김춘자의정부부대찌개", "cat": "한식", "menu": "찌개,전골", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-대청마루", "name": "대청마루", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-더다미", "name": "더다미", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-서해쭈꾸미", "name": "서해쭈꾸미", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-여의도부대찌개", "name": "여의도부대찌개", "cat": "한식", "menu": "찌개,전골", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-여의도사골칼국수", "name": "여의도사골칼국수", "cat": "한식", "menu": "칼국수", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-오마니", "name": "오마니", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-오한수우육면가직영본점", "name": "오한수우육면가 직영본점", "cat": "중식", "menu": "중식", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "yugane", "name": "유가네손맛포차", "cat": "한식", "menu": "회덮밥·바지락칼국수·제육 (포장마차식)", "price": "", "addr": "국회대로62길 23", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-고향집", "name": "고향집", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 25", "bldg": "한국교육시설안전원", "zone": "alley", "src": "", "q": ""},
  {"id": "k-본우리반상국회의사당역점", "name": "본우리반상 국회의사당역점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 25", "bldg": "한국교육시설안전원", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-우제리막국수여의도본점", "name": "우제리막국수 여의도본점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 25", "bldg": "한국교육시설안전원", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-참배나무골오리집여의도점", "name": "참배나무골오리집 여의도점", "cat": "한식", "menu": "오리", "price": "", "addr": "국회대로62길 25", "bldg": "한국교육시설안전원", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-항아리갈비탕여의도점", "name": "항아리갈비탕 여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 25", "bldg": "한국교육시설안전원", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-일미", "name": "일미", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로62길 5", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-사조회참치여의광장점", "name": "사조회참치 여의광장점", "cat": "한식", "menu": "사조회참치", "price": "", "addr": "국회대로62길 9", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-여의도버섯칼국수", "name": "여의도 버섯칼국수", "cat": "한식", "menu": "칼국수", "price": "", "addr": "국회대로62길 9", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-갓잇여의도점", "name": "갓잇 여의도점", "cat": "양식", "menu": "멕시칸,브라질", "price": "", "addr": "국회대로66길 11-4", "bldg": "현대마에스트로", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-리나스국회의사당역점", "name": "리나스 국회의사당역점", "cat": "양식", "menu": "리나스", "price": "", "addr": "국회대로66길 11-4", "bldg": "현대마에스트로", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-오치교반여의도점", "name": "오치교반 여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로66길 11-4", "bldg": "현대마에스트로", "zone": "alley", "src": "", "q": ""},
  {"id": "k-마보야", "name": "마보야", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-백년찌개집1971", "name": "백년찌개집1971", "cat": "한식", "menu": "찌개,전골", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-싸다김밥서여의도점", "name": "싸다김밥 서여의도점", "cat": "분식·기타", "menu": "싸다김밥", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-예당", "name": "예당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-오늘은즉떡3호점", "name": "오늘은즉떡 3호점", "cat": "분식·기타", "menu": "떡볶이", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-추양옥여의도점", "name": "추양옥 여의도점", "cat": "한식", "menu": "추어", "price": "", "addr": "국회대로66길 17", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-심경희라라랜드여의도점", "name": "심경희라라랜드 여의도점", "cat": "한식", "menu": "갈비", "price": "", "addr": "국회대로66길 19", "bldg": "", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-탑와플앤버거", "name": "탑와플앤버거", "cat": "분식·기타", "menu": "간식", "price": "", "addr": "국회대로66길 23", "bldg": "산정빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "ido", "name": "이도식당", "cat": "한식", "menu": "해물샤브·해물칼국수·국수전골", "price": "1.8만/인", "addr": "국회대로68길 11", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-민소한우서여의도점", "name": "민소한우 서여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로68길 17", "bldg": "해운빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-연희식당", "name": "연희식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로68길 17", "bldg": "해운빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-이태원천상서여의도점", "name": "이태원천상 서여의도점", "cat": "일식", "menu": "일식집", "price": "", "addr": "국회대로68길 17", "bldg": "해운빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "seyang", "name": "세양원", "cat": "중식", "menu": "점심특선·마파두부", "price": "점심특선 저가", "addr": "국회대로68길 18", "bldg": "금영빌딩", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-가야한정식", "name": "가야한정식", "cat": "한식", "menu": "한정식", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-광씨네전주콩나물국밥", "name": "광씨네전주콩나물국밥", "cat": "한식", "menu": "국밥", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-꽁당보리네", "name": "꽁당보리네", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-본터대구탕", "name": "본터대구탕", "cat": "한식", "menu": "매운탕,해물탕", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-진1926여의도점", "name": "진1926 여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "homerest", "name": "홈레스토랑", "cat": "양식", "menu": "퓨전 양식", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "sogong", "name": "소공동뚝배기 여의도점", "cat": "한식", "menu": "제육볶음·뚝배기 (07:00~)", "price": "", "addr": "국회대로68길 23 1층", "bldg": "정원빌딩", "zone": "alley", "src": "다이닝코드 맛4.5", "q": "", "franchise": true},
  {"id": "k-대동장어여의도점", "name": "대동장어 여의도점", "cat": "한식", "menu": "장어", "price": "", "addr": "국회대로68길 24", "bldg": "", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-달구지", "name": "달구지", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로68길 7", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-다옴", "name": "다옴", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로70길 12", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-스시이찌국회의사당점", "name": "스시이 찌 국회의사당점", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로70길 12", "bldg": "", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-kfc여의도점", "name": "KFC 여의도점", "cat": "양식", "menu": "KFC", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-갯벌의조개여의도점", "name": "갯벌의조개 여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-소호정여의도국회의사당점", "name": "소호정 여의도국회의사당점", "cat": "한식", "menu": "소호정", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-솔직한우여의도점", "name": "솔직 한우 여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-일미온", "name": "일미온", "cat": "한식", "menu": "해장국", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-한국의밥상", "name": "한국의밥상", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 15-1", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "kimmyeongja", "name": "김명자굴국밥 국회의사당점", "cat": "한식", "menu": "굴국밥·굴떡국 (06:00~)", "price": "1만~1.4만", "addr": "국회대로70길 15-1 지하1층", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-경복궁서여의도점", "name": "경복궁 서여의도점", "cat": "한식", "menu": "경복궁", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-돈돈번", "name": "돈돈번", "cat": "한식", "menu": "삼겹살", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-리도멘", "name": "리도멘", "cat": "일식", "menu": "일본식라면", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-아임샐러드", "name": "아임샐러드", "cat": "분식·기타", "menu": "샐러드", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-연타발여의도점", "name": "연타발 여의도점", "cat": "한식", "menu": "연타발", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-팔팔미담여의도점", "name": "팔팔미담 여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 18", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "kadonmari", "name": "카돈마리", "cat": "일식", "menu": "돈까스+쌀국수", "price": "", "addr": "국회대로70길 18 303호", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "boseung", "name": "보승회관 여의도국회의사당점", "cat": "한식", "menu": "순대국", "price": "", "addr": "국회대로70길 18 지하 (추정)", "bldg": "한양빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "mugong", "name": "무공돈까스 서여의도점", "cat": "일식", "menu": "돈까스·코돈부르", "price": "1.2만~", "addr": "국회대로70길 18 지하1층 1·2호", "bldg": "한양빌딩", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "k-금룡", "name": "금룡", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-꽃새담여의도직영점", "name": "꽃새담 여의도직영점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-밍웬", "name": "밍웬", "cat": "중식", "menu": "중식", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-써브웨이여의도국회의사당점", "name": "써브웨이 여의도국회의사당점", "cat": "양식", "menu": "써브웨이", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-어울림", "name": "어울림", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-전철우닭뼈", "name": "전철우닭뼈", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-향촌흑염소국회의사당점", "name": "향촌흑염소 국회의사당점", "cat": "한식", "menu": "사철탕,영양탕", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-혼복집", "name": "혼복집", "cat": "한식", "menu": "복어", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "siena", "name": "시에나프리모", "cat": "양식", "menu": "파스타·피자·리소토", "price": "", "addr": "국회대로70길 19 B106호", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-금강식당", "name": "금강식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 22", "bldg": "금강빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-비비샐러드", "name": "비비샐러드", "cat": "분식·기타", "menu": "샐러드", "price": "", "addr": "국회대로70길 22", "bldg": "금강빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-삼원정", "name": "삼원정", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로70길 22", "bldg": "금강빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-오묘서여의도점", "name": "오묘 서여의도점", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로70길 22", "bldg": "금강빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "daeboreum", "name": "대보름", "cat": "한식", "menu": "남도음식 정식 (이모카세)", "price": "1.5만", "addr": "국회대로70길 22 지하1층", "bldg": "금강빌딩", "zone": "alley", "src": "다이닝코드 맛5.0", "q": ""},
  {"id": "k-권서방네순대국", "name": "권서방네순대국", "cat": "한식", "menu": "순대", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-금원삼계탕", "name": "금원삼계탕", "cat": "한식", "menu": "삼계탕", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-농농", "name": "농농", "cat": "아시안", "menu": "아시아음식", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-다미", "name": "다미", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-동아분식", "name": "동아분식", "cat": "분식·기타", "menu": "분식", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-버드나무", "name": "버드나무", "cat": "한식", "menu": "오리", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-속초해물탕", "name": "속초해물탕", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "yangji", "name": "여의도양지탕 본관", "cat": "한식", "menu": "양지탕 (44년 노포, 육수·밥 무한)", "price": "특탕 1.4만", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "다이닝코드 71점", "q": ""},
  {"id": "k-옥된장서여의도점", "name": "옥된장 서여의도점", "cat": "한식", "menu": "옥된장", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-원조감자탕일미집국회의사당점", "name": "원조감자탕 일미집 국회의사당점", "cat": "한식", "menu": "감자탕", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-장수집", "name": "장수집", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-진성옥", "name": "진성옥", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-황금복국여의도점", "name": "황금복국 여의도점", "cat": "한식", "menu": "복어", "price": "", "addr": "국회대로70길 7", "bldg": "동아빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "dokto", "name": "독토", "cat": "한식", "menu": "김치·된장·곱창전골·제육쌈밥", "price": "", "addr": "국회대로70길 7 지하", "bldg": "동아빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-낙지한마리수제비", "name": "낙지한마리수제비", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": ""},
  {"id": "k-남도제철음식점", "name": "남도제철음식점", "cat": "한식", "menu": "한정식", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-미야비", "name": "미야비", "cat": "일식", "menu": "일식집", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-신당양곱창", "name": "신당양곱창", "cat": "한식", "menu": "곱창,막창", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": ""},
  {"id": "jinjin", "name": "진진만두 국회점", "cat": "한식", "menu": "만두국·어복쟁반", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": ""},
  {"id": "k-팔만식당1970", "name": "팔만식당1970", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": ""},
  {"id": "k-헤비스테이크여의도점", "name": "헤비스테이크 여의도점", "cat": "양식", "menu": "양식", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-히비끼", "name": "히비끼", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": ""},
  {"id": "k-고향옥얼큰순대국", "name": "고향옥얼큰순대국", "cat": "한식", "menu": "고향옥얼큰순대국", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-동해수산", "name": "동해수산", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "k-병천향토순대", "name": "병천향토순대", "cat": "한식", "menu": "순대", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "k-새싹", "name": "새싹", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "k-용화양꼬치마라탕", "name": "용화양꼬치마라탕", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-포리타", "name": "포리타", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "suage", "name": "스아게 여의도점", "cat": "일식", "menu": "삿포로식 스프카레", "price": "", "addr": "국회대로72길 17 203호", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "eomnamu", "name": "엄나무집", "cat": "한식", "menu": "닭갈비·볶음밥", "price": "", "addr": "국회대로72길 17 208-1호", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "oebaek", "name": "외백", "cat": "중식", "menu": "룸 중식 (고급)", "price": "", "addr": "국회대로72길 17 301~311호", "bldg": "KCC파크타운", "zone": "alley", "src": "가격 미확인(고급 가능성, 확인 필요)", "q": ""},
  {"id": "k-경희면옥여의도점", "name": "경희면옥 여의도점", "cat": "한식", "menu": "냉면", "price": "", "addr": "국회대로72길 21", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-본도시락서여의도점", "name": "본도시락 서여의도점", "cat": "분식·기타", "menu": "본도시락", "price": "", "addr": "국회대로72길 21", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-회동", "name": "회동", "cat": "한식", "menu": "회", "price": "", "addr": "국회대로72길 21", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-생태명가여의도점", "name": "생태명가 여의도점", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로72길 22", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-자금성", "name": "자금성", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로72길 22", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-한방대가삼계탕여의도점", "name": "한방대가삼계탕 여의도점", "cat": "한식", "menu": "삼계탕", "price": "", "addr": "국회대로72길 22", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-이즈미", "name": "이즈미", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로72길 4", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-고봉삼계탕", "name": "고봉삼계탕", "cat": "한식", "menu": "삼계탕", "price": "", "addr": "국회대로72길 5", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-양산도서여의도점", "name": "양산도 서여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로72길 6", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-창우식당", "name": "창우식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로72길 6", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-삼삼뼈국여의도점", "name": "삼삼뼈국 여의도점", "cat": "한식", "menu": "감자탕", "price": "", "addr": "국회대로74길 10", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-서울안심정육서여의도점", "name": "서울안심정육 서여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로74길 10", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-본죽비빔밥cafe서여의도점", "name": "본죽&비빔밥cafe 서여의도점", "cat": "한식", "menu": "본죽&비빔밥cafe", "price": "", "addr": "국회대로74길 12", "bldg": "남중빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "eommakal", "name": "엄마손칼국수", "cat": "한식", "menu": "칼국수·콩국수", "price": "", "addr": "국회대로74길 12", "bldg": "", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-원할머니보쌈족발여의도점", "name": "원할머니보쌈족발 여의도점", "cat": "한식", "menu": "원할머니보쌈족발", "price": "", "addr": "국회대로74길 12", "bldg": "남중빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-청록미나리식당여의도점", "name": "청록미나리식당 여의도점", "cat": "분식·기타", "menu": "청록미나리식당", "price": "", "addr": "국회대로74길 12", "bldg": "남중빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-풍년닭도리탕여의도점", "name": "풍년닭도리탕 여의도점", "cat": "한식", "menu": "닭요리", "price": "", "addr": "국회대로74길 12", "bldg": "남중빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-동우황태서여의도점", "name": "동우황태 서여의도점", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로74길 19", "bldg": "동우국제빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "dongwoo", "name": "동우황태북어국 본점", "cat": "한식", "menu": "황태해장국 (06:00~15:00)", "price": "", "addr": "국회대로74길 19", "bldg": "동우국제빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-만나", "name": "만나", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로74길 19", "bldg": "동우국제빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "kwak", "name": "곽수산", "cat": "한식", "menu": "회덮밥·물회·생대구탕", "price": "1.2만~1.8만", "addr": "국회대로74길 19 지하1층", "bldg": "동우국제빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-경성양꼬치여의도점", "name": "경성양꼬치 여의도점", "cat": "중식", "menu": "경성양꼬치", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-부안육비서여의도점", "name": "부안육비 서여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-스시츠키", "name": "스시츠키", "cat": "일식", "menu": "초밥,롤", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-슬로우캘리국회대로점", "name": "슬로우캘리 국회대로점", "cat": "분식·기타", "menu": "슬로우캘리", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-여의도미나리삼겹서여의도점", "name": "여의도미나리삼겹 서여의도점", "cat": "한식", "menu": "삼겹살", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-온적", "name": "온적", "cat": "양식", "menu": "양식", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-용산옥부대찌개치즈닭갈비여의도직영점", "name": "용산옥부대찌개&치즈닭갈비 여의도 직영점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-이수쭈꾸미서여의도점", "name": "이수쭈꾸미 서여의도점", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-저스트텐동여의도점", "name": "저스트텐동 여의도점", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-정오", "name": "정오", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-제이렘333피제리아", "name": "제이렘333피제리아", "cat": "양식", "menu": "피자", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-차이나프로", "name": "차이나프로", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-채선당도시락샐러드서여의도점", "name": "채선당 도시락&샐러드 서여의도점", "cat": "분식·기타", "menu": "도시락", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-코코이찌방야국회의사당역점", "name": "코코이찌방야 국회의사당역점", "cat": "분식·기타", "menu": "코코이찌방야", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-클래식", "name": "클래식", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-함경진순대", "name": "함경진순대", "cat": "한식", "menu": "순대", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "k-해동복국서여의도점", "name": "해동복국 서여의도점", "cat": "한식", "menu": "복어", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-해운대속씨원한대구탕여의도점", "name": "해운대속씨원한대구탕 여의도점", "cat": "한식", "menu": "매운탕,해물탕", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-호앙비엣여의도점", "name": "호앙비엣 여의도점", "cat": "아시안", "menu": "베트남음식", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "yangmani", "name": "양마니 여의도점", "cat": "한식", "menu": "양곰탕·양밥", "price": "1.4만", "addr": "국회대로74길 20 2층", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "gyerim", "name": "종로계림닭도리탕원조 국회의사당점", "cat": "한식", "menu": "마늘닭도리탕", "price": "", "addr": "국회대로74길 20 2층", "bldg": "맨하탄21상가", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "k-가양", "name": "가양", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-남원추어탕", "name": "남원추어탕", "cat": "한식", "menu": "추어", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-맨하탄피자", "name": "맨하탄피자", "cat": "양식", "menu": "피자", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-수석식당", "name": "수석식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "k-양은이네여의도점", "name": "양은이네 여의도점", "cat": "한식", "menu": "양은이네", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-청기와타운여의도점", "name": "청기와타운 여의도점", "cat": "한식", "menu": "갈비", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "carnival", "name": "카니발피자 서여의도점", "cat": "양식", "menu": "피자·파스타", "price": "", "addr": "국회대로74길 9 206호", "bldg": "삼보빌딩", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "masam", "name": "마삼계탕 여의도점", "cat": "한식", "menu": "부추오리주물럭·마삼계탕", "price": "1.5만", "addr": "국회대로74길 9 지하1층 107호", "bldg": "삼보빌딩", "zone": "alley", "src": "다이닝코드 74~77점", "q": "", "franchise": true},
  {"id": "eommason", "name": "엄마손분식", "cat": "분식·기타", "menu": "백반", "price": "", "addr": "국회대로76가길 11", "bldg": "초원상가", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "ri153", "name": "리153", "cat": "중식", "menu": "중식뷔페 (평일 11~14시, 100인 한정)", "price": "1만", "addr": "국회대로76가길 11 지하1층 5호", "bldg": "초원상가", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-해초가", "name": "해초가", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "국회대로76길 10", "bldg": "기독교침례회총회빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "jungin", "name": "정인면옥 본점", "cat": "한식", "menu": "평양냉면·만두", "price": "1.5만~1.7만", "addr": "국회대로76길 10 1층", "bldg": "기독교침례회총회빌딩", "zone": "alley", "src": "미쉐린 빕구르망 · 다이닝코드 ★4.0", "q": ""},
  {"id": "k-델리순복음교회샬롬관점", "name": "델리 순복음교회샬롬관점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 15", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-가시리여의도점", "name": "가시리 여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "", "q": ""},
  {"id": "k-여우애김밥여의도점", "name": "여우애김밥 여의도점", "cat": "분식·기타", "menu": "분식", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-푸에르코국회의사당", "name": "푸에르코 국회의사당", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "", "q": ""},
  {"id": "shanghao", "name": "샹하오", "cat": "중식", "menu": "호텔 중식 런치세트", "price": "1만~2만 (런치)", "addr": "국회대로76길 16 2층", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "일 휴무 · 카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-다모아산채", "name": "다모아산채", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-맛사랑", "name": "맛사랑", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-무지개", "name": "무지개", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-상상부엌", "name": "상상부엌", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-섬마을식당", "name": "섬마을식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-스시란", "name": "스시란", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-스시아이", "name": "스시아이", "cat": "일식", "menu": "초밥,롤", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-오성해물탕", "name": "오성해물탕", "cat": "한식", "menu": "매운탕,해물탕", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-장호왕곱창김치찌개", "name": "장호왕곱창&김치찌개", "cat": "한식", "menu": "곱창,막창", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "k-전진샤브샤브", "name": "전진 샤브샤브", "cat": "한식", "menu": "샤브샤브", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-포케올데이서여의도점", "name": "포케올데이 서여의도점", "cat": "분식·기타", "menu": "포케올데이", "price": "", "addr": "국회대로76길 18", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "hohwa", "name": "호화대반점", "cat": "중식", "menu": "노포 짜장·탕수육", "price": "1만원 안팎", "addr": "국회대로76길 18 지하1층", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "k-전철우제주해장고향랭면국회의사당점", "name": "전철우제주해장고향랭면 국회의사당점", "cat": "한식", "menu": "냉면", "price": "", "addr": "국회대로76길 22", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "seolyeon", "name": "설연향", "cat": "중식", "menu": "차돌짬뽕·유니짜장", "price": "", "addr": "국회대로76길 33 지하1층", "bldg": "중앙보훈회관", "zone": "alley", "src": "다이닝코드 58점 · 카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  // ── 국회대로 본선 (LG에클라트·금산빌딩·파라곤)
  {"id": "k-국회보쌈", "name": "국회보쌈", "cat": "한식", "menu": "족발,보쌈", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-금산민속손칼국수", "name": "금산민속손칼국수", "cat": "한식", "menu": "칼국수", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-금산생대구", "name": "금산생대구", "cat": "한식", "menu": "매운탕,해물탕", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-너섬", "name": "너섬", "cat": "한식", "menu": "찌개,전골", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-여의도식당", "name": "여의도식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-여의도장어", "name": "여의도장어", "cat": "한식", "menu": "장어", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-여의명가", "name": "여의명가", "cat": "한식", "menu": "국밥", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-은성순대국", "name": "은성순대국", "cat": "한식", "menu": "순대", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-은주설렁탕", "name": "은주설렁탕", "cat": "한식", "menu": "설렁탕", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "k-참복집", "name": "참복집", "cat": "한식", "menu": "복어", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-한류관", "name": "한류관", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "dongnam", "name": "동남집", "cat": "한식", "menu": "양지곰탕", "price": "", "addr": "국회대로 750 1층", "bldg": "금산빌딩", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "jeonjujip", "name": "전주집", "cat": "한식", "menu": "김치찌개·김치전골·계란말이", "price": "", "addr": "국회대로 750 1층 (동명 타점포 가능성, 확인 필요)", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "samdo", "name": "삼도일식", "cat": "일식", "menu": "일식 정식·대구탕 (룸)", "price": "", "addr": "국회대로 750 지하1층", "bldg": "금산빌딩 (국회 정문 맞은편)", "zone": "main", "src": "가격 미확인(고급 가능성, 확인 필요) · 점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-간사이스타", "name": "간사이스타", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-금화쿵푸", "name": "금화쿵푸", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-농민백암왕순대", "name": "농민백암왕순대", "cat": "한식", "menu": "순대", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-다원", "name": "다원", "cat": "중식", "menu": "중국요리", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-돈해진미", "name": "돈해진미", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-마초갈비국회의사당점", "name": "마초갈비 국회의사당점", "cat": "한식", "menu": "갈비", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-방배김밥여의도점", "name": "방배김밥 여의도점", "cat": "분식·기타", "menu": "방배김밥", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-쉐나스픽by마꽁이네국회점", "name": "쉐나스픽 by.마꽁이네 국회점", "cat": "분식·기타", "menu": "분식", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-스시나고미", "name": "스시나고미", "cat": "일식", "menu": "초밥,롤", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-스타우동오뎅", "name": "스타우동오뎅", "cat": "일식", "menu": "돈까스,우동", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-오가네전주콩나물해장국", "name": "오가네 전주콩나물해장국", "cat": "한식", "menu": "해장국", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-전주현대옥서울국회의사당점", "name": "전주현대옥 서울국회의사당점", "cat": "한식", "menu": "전주현대옥", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-정직유부서여의도점", "name": "정직유부 서여의도점", "cat": "일식", "menu": "정직유부", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-조pd키친", "name": "조PD키친", "cat": "분식·기타", "menu": "도시락", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-조선보울여의도점", "name": "조선보울 여의도점", "cat": "분식·기타", "menu": "샐러드", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-킹콩부대찌개서여의도점", "name": "킹콩부대찌개 서여의도점", "cat": "한식", "menu": "킹콩부대찌개", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-향토식당", "name": "향토식당", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-향토칼국수", "name": "향토칼국수", "cat": "한식", "menu": "칼국수", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "k-힐담채", "name": "힐담채", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "kimsambo", "name": "김삼보 여의도점", "cat": "한식", "menu": "1인 김치찌개·솥밥 (24시)", "price": "", "addr": "국회대로 780 1층", "bldg": "LG여의도에클라트", "zone": "main", "src": "1번 출구 156m", "q": "", "franchise": true},
  {"id": "basburger", "name": "바스버거 국회의사당점", "cat": "양식", "menu": "수제버거·감자칩", "price": "", "addr": "국회대로 780 지하1층", "bldg": "LG여의도에클라트", "zone": "main", "src": "다이닝코드 ★4.5 · 1번 출구 2분", "q": "", "franchise": true},
  {"id": "sunnam", "name": "순남시래기 서여의도점", "cat": "한식", "menu": "시래기국·수육정식", "price": "8천~1.3만", "addr": "국회대로 780 지하1층", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-금조온흑염소전문점국회의사당본점", "name": "금조온 흑염소 전문점 국회의사당 본점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-대방골", "name": "대방골", "cat": "한식", "menu": "한정식", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-어진여의도점", "name": "어진 여의도점", "cat": "한식", "menu": "냉면", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": ""},
  {"id": "k-전설의우대갈비여의도직영점", "name": "전설의우대갈비 여의도직영점", "cat": "한식", "menu": "갈비", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-차이윤서여의도점", "name": "차이윤 서여의도점", "cat": "중식", "menu": "중식", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": ""},
  {"id": "k-창고43서여의도점", "name": "창고43 서여의도점", "cat": "한식", "menu": "한식", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-테트리스찜닭영등포점", "name": "테트리스찜닭 영등포점", "cat": "한식", "menu": "닭요리", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "k-화담", "name": "화담", "cat": "일식", "menu": "일식", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": ""},
  {"id": "wanttuk", "name": "완뚝순두부 여의도점", "cat": "한식", "menu": "순두부·돌솥밥 (24시)", "price": "", "addr": "국회대로 800 1층", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": "", "franchise": true},
  // ── 국회의사당역 3~6번 출구 (익스콘·더샵아일랜드파크)
  {"id": "k-마리짱국회의사당역점", "name": "마리짱 국회의사당역점", "cat": "분식·기타", "menu": "분식", "price": "", "addr": "국회대로 지하 758", "bldg": "국회의사당역 역사 안", "zone": "station", "src": "", "q": ""},
  {"id": "gwibin", "name": "귀빈밥상", "cat": "한식", "menu": "9첩 백반", "price": "", "addr": "은행로 3 지하 식당가", "bldg": "익스콘벤처타워", "zone": "station", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "k-갓포아키여의도점", "name": "갓포아키 여의도점", "cat": "일식", "menu": "일식", "price": "", "addr": "의사당대로 16", "bldg": "글래드호텔 여의도", "zone": "station", "src": "", "q": ""},
  {"id": "k-다원한정식", "name": "다원한정식", "cat": "한식", "menu": "한정식", "price": "", "addr": "의사당대로 21", "bldg": "한국평가데이터", "zone": "station", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-권스시", "name": "권스시", "cat": "일식", "menu": "초밥,롤", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": ""},
  {"id": "k-마포수제비", "name": "마포수제비", "cat": "한식", "menu": "수제비", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-만복집국회의사당점", "name": "만복집 국회의사당점", "cat": "한식", "menu": "만복집", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-버텍스여의도점", "name": "버텍스 여의도점", "cat": "양식", "menu": "퓨전요리", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-어도일식여의도", "name": "어도일식 여의도", "cat": "일식", "menu": "일식", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-여의나루순대족발", "name": "여의나루순대족발", "cat": "한식", "menu": "족발,보쌈", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-우섬", "name": "우섬", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": ""},
  {"id": "jeongdam", "name": "정담긴추어탕", "cat": "한식", "menu": "추어탕", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": ""},
  {"id": "k-해돈식당", "name": "해돈식당", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "beyond", "name": "비욘드비엣남 국회의사당점", "cat": "아시안", "menu": "쌀국수", "price": "", "addr": "의사당대로 26 107호", "bldg": "더하우스소호", "zone": "station", "src": "4번 출구 2분 · 다이닝코드 맛4.8", "q": "", "franchise": true},
  {"id": "jeonjubonga", "name": "전주본가", "cat": "한식", "menu": "전주콩나물국밥 (08:00~)", "price": "9천", "addr": "의사당대로 26 지하1층", "bldg": "스타벅스 빌딩 지하", "zone": "station", "src": "다이닝코드 ★4.0", "q": "", "franchise": true},
  {"id": "mucheong", "name": "무청감자탕 국회의사당점", "cat": "한식", "menu": "감자탕·뼈해장국", "price": "", "addr": "의사당대로 26 지하1층 B113호", "bldg": "더하우스소호", "zone": "station", "src": "4번 출구 97m", "q": "", "franchise": true},
  {"id": "k-375시그니처여의도점", "name": "37.5 시그니처 여의도점", "cat": "양식", "menu": "양식", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-8번대물집", "name": "8번대물집", "cat": "한식", "menu": "회", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-구이구이여의도본점", "name": "구이구이 여의도본점", "cat": "한식", "menu": "해물,생선", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-구포국수세번째이야기", "name": "구포국수세번째이야기", "cat": "한식", "menu": "국수", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-김가네여의도kbs본관점", "name": "김가네 여의도KBS본관점", "cat": "분식·기타", "menu": "김가네", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-꼬소한부뚜막kbs본관직영점", "name": "꼬소한부뚜막 KBS본관직영점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-도약", "name": "도약", "cat": "한식", "menu": "삼겹살", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "lishan", "name": "리샨 여의도점", "cat": "중식", "menu": "차돌짬뽕·삼선짬뽕·런치코스", "price": "1.2만~3.2만", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "다이닝코드 73점", "q": ""},
  {"id": "k-미스터초우본점", "name": "미스터초우 본점", "cat": "한식", "menu": "한식", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-백진닭곰탕", "name": "백진닭곰탕", "cat": "한식", "menu": "곰탕", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-봉채직화제육닭볶음탕", "name": "봉채직화제육닭볶음탕", "cat": "한식", "menu": "닭요리", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-소울갈비여의도점", "name": "소울갈비 여의도점", "cat": "한식", "menu": "육류,고기", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "점심 가격 확인 필요(2만 원 초과 가능)", "q": "", "franchise": true},
  {"id": "k-슬로우캘리여의도kbs본관점", "name": "슬로우캘리 여의도KBS본관점", "cat": "분식·기타", "menu": "슬로우캘리", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-신의주찹쌀순대여의도점", "name": "신의주찹쌀순대 여의도점", "cat": "한식", "menu": "신의주찹쌀순대", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-엉터리해장국서여의도점", "name": "엉터리해장국 서여의도점", "cat": "한식", "menu": "해장국", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-장독대김치찌개", "name": "장독대김치찌개", "cat": "한식", "menu": "찌개,전골", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-틈새라면서여의도점", "name": "틈새라면 서여의도점", "cat": "분식·기타", "menu": "틈새라면", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "k-프랭크버거여의도kbs점", "name": "프랭크버거 여의도KBS점", "cat": "양식", "menu": "프랭크버거", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "halong", "name": "하롱베이의하루 여의도본점", "cat": "아시안", "menu": "베트남 쌀국수", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "haebim", "name": "해빔 여의도점", "cat": "한식", "menu": "꽃게살비빔밥·꽃게탕", "price": "", "addr": "의사당대로 38 101동 111호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "hancheop", "name": "한첩", "cat": "한식", "menu": "보양순대국밥·만두", "price": "1.1만", "addr": "의사당대로 38 101동 1층 103호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "4번 출구 앞", "q": "", "franchise": true},
  {"id": "gosutaco", "name": "고수타코 여의도KBS점", "cat": "아시안", "menu": "타코·부리또", "price": "", "addr": "의사당대로 38 102동 107호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "다이닝코드 ★4.3", "q": "", "franchise": true},
  {"id": "iru", "name": "이루 kbs서여의도점", "cat": "중식", "menu": "화교 3대 중식 (짜장·간짜장·새우교자)", "price": "8천~1.1만", "addr": "의사당대로 38 102동 124호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "다이닝코드 53점", "q": "", "franchise": true},
  {"id": "haedamon", "name": "해담온", "cat": "일식", "menu": "제주흑돼지 돈가스·연어덮밥", "price": "1.4만~1.7만", "addr": "의사당대로 38 103동 1층 104호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "다이닝코드 68~70점 · 카카오 조회에 없음 · 영업 확인 필요", "q": ""},
  {"id": "gradimon", "name": "그리디몬버거", "cat": "양식", "menu": "수제버거", "price": "", "addr": "의사당대로 38 109호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": ""},
  {"id": "sobaudon", "name": "여의도소바우동", "cat": "일식", "menu": "소바·우동", "price": "", "addr": "의사당대로 38 1층", "bldg": "더샵아일랜드파크 (KBS본관 앞)", "zone": "station", "src": "", "q": ""},
  {"id": "k-한국수여의도점", "name": "한국수 여의도점", "cat": "한식", "menu": "국수", "price": "", "addr": "의사당대로 8", "bldg": "", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "sawi", "name": "사위식당 여의도점", "cat": "한식", "menu": "낙곱새·손만두", "price": "", "addr": "주소 미확인 (건물 2층)", "bldg": "", "zone": "station", "src": "다이닝코드 ★4.7 · 카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  // ── 국회 경내·KBS
  {"id": "k-고샌드kbs점", "name": "고샌드 KBS점", "cat": "양식", "menu": "샌드위치", "price": "", "addr": "여의공원로 13", "bldg": "KBS", "zone": "west", "src": "", "q": "", "franchise": true},
  {"id": "k-오밍고박스", "name": "오밍고박스", "cat": "한식", "menu": "한식", "price": "", "addr": "여의공원로 13", "bldg": "KBS", "zone": "west", "src": "", "q": "", "franchise": true},
];
