// CCMM 디저트 룰렛 후보 데이터 (cafe/index.html 이 읽음)
// id 는 반드시 "cafe-" 로 시작 (점심 룰렛과 같은 구글 시트를 쓰므로 겹치지 않게)
// cat : 커피 · 디저트 · 베이커리 · 빙수·아이스크림 · 차·음료
window.META = {
  "zones": [
    {
      "id": "ccmm",
      "label": "CCMM빌딩 안·앞"
    },
    {
      "id": "bank",
      "label": "은행로 (중기중앙회·KDB·정우/안원빌딩)"
    },
    {
      "id": "alley",
      "label": "국회대로 62~76길 골목 (순복음교회 뒤)"
    },
    {
      "id": "main",
      "label": "국회대로 본선 (LG에클라트·금산빌딩·파라곤)"
    },
    {
      "id": "station",
      "label": "국회의사당역 출구 앞 (익스콘·더샵아일랜드파크)"
    },
    {
      "id": "west",
      "label": "국회 경내·KBS",
      "inScope": false
    }
  ],
  "footer": "범위: 여의도공원 서측(여의공원로 기준) ~ 국회의사당역 출구 앞. 국회 경내·KBS는 기본 제외. 카카오맵 조회(2026-09-28) 기준이며 비고에 '확인 필요'가 있는 곳은 폐점·이전 가능성이 있습니다. 목록 수정은 cafe/data.js."
};

window.RESTAURANTS = [
  // ── CCMM빌딩 안·앞
  {"id": "cafe-sbux-park", "name": "스타벅스 여의도공원R점", "cat": "커피", "menu": "리저브 원두 커피", "price": "", "addr": "여의공원로 101 1층", "bldg": "CCMM빌딩", "zone": "ccmm", "src": "월~목 06:30~22:00", "q": "", "franchise": true},
  // ── 은행로 (중기중앙회·KDB·정우/안원빌딩)
  {"id": "cafe-k22547052", "name": "스타벅스 여의도일신점", "cat": "커피", "menu": "", "price": "", "addr": "은행로 11", "bldg": "일신빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k814443507", "name": "나이스데이", "cat": "커피", "menu": "", "price": "", "addr": "은행로 17", "bldg": "NICE 빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k1654954142", "name": "노던레드", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k722634895", "name": "노슬립커피 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k120686621", "name": "델모어", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k1459697187", "name": "밀키웨이밀크티 여의도점", "cat": "차·음료", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "cafe-bruda", "name": "브루다커피 서여의도점", "cat": "커피", "menu": "저가 커피", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "패스오더 등록만 확인", "q": "", "franchise": true},
  {"id": "cafe-k404533620", "name": "브루클린커피", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k1898755170", "name": "아사르", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k1860804898", "name": "이코복스커피스튜디오 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1955512833", "name": "정우커피", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k20195802", "name": "카페스터닝", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k66553172", "name": "테이스티박스", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-tenpercent", "name": "텐퍼센트커피 서여의도점", "cat": "커피", "menu": "스페셜티 아메리카노", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "커피기업과 같은 주소로 검색됨 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-k1559226513", "name": "플로리다", "cat": "커피", "menu": "", "price": "", "addr": "은행로 29", "bldg": "정우빌딩", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-coffeegiup", "name": "커피기업 여의도직영점", "cat": "커피", "menu": "아인슈페너·스노우비엔나", "price": "", "addr": "은행로 29 1층 13호", "bldg": "정우빌딩", "zone": "bank", "src": "텐퍼센트커피와 같은 주소로 검색됨 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-sweetcharging", "name": "스윗차징", "cat": "베이커리", "menu": "빵", "price": "", "addr": "은행로 29 1층 21호", "bldg": "정우빌딩", "zone": "bank", "src": "매일 07:00~20:00 · 다이닝코드 ★5.0", "q": ""},
  {"id": "cafe-k2143707125", "name": "투흐티", "cat": "차·음료", "menu": "", "price": "", "addr": "은행로 3", "bldg": "익스콘벤처타워", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-artisee", "name": "아티제 여의도공원점", "cat": "베이커리", "menu": "인절미 팥빙수·생크림 케이크·크로아상", "price": "", "addr": "은행로 30 신관 1층", "bldg": "중소기업중앙회", "zone": "bank", "src": "07:00~21:30", "q": "", "franchise": true},
  {"id": "cafe-k12772378", "name": "카페오가닉 여의도본점", "cat": "커피", "menu": "", "price": "", "addr": "은행로 37", "bldg": "한국기계산업진흥회(기계회관)", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-rollpi", "name": "롤피", "cat": "커피", "menu": "수제청 음료·커피", "price": "", "addr": "은행로 37 신관 1층 (검색 결과 상이, 확인 필요)", "bldg": "한국기계산업진흥회", "zone": "bank", "src": "", "q": ""},
  {"id": "cafe-k533657869", "name": "이디야커피 한국수출입은행점", "cat": "커피", "menu": "", "price": "", "addr": "은행로 38", "bldg": "한국수출입은행", "zone": "bank", "src": "", "q": "", "franchise": true},
  {"id": "cafe-dutchnbean", "name": "더치앤빈 여의도공원점", "cat": "커피", "menu": "흑당카페라떼·더치커피", "price": "", "addr": "은행로 54 1층 105호", "bldg": "", "zone": "bank", "src": "평일 07:00~17:00 · 토 휴무", "q": "", "franchise": true},
  // ── 국회대로 62~76길 골목 (순복음교회 뒤)
  {"id": "cafe-k1402698579", "name": "커피나인 KBS점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로62길 11", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k2072259663", "name": "매머드익스프레스 여의도스카우트빌딩점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로62길 14", "bldg": "한국스카우트연맹빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k2146892654", "name": "투썸플레이스 여의도광복회관점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로62길 15", "bldg": "광복회관", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1257048618", "name": "우드스톤 여의도", "cat": "커피", "menu": "", "price": "", "addr": "국회대로62길 21", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1462920106", "name": "웨이즈커피 로스터스", "cat": "커피", "menu": "", "price": "", "addr": "국회대로62길 7", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k9752530", "name": "로얄호스트커피", "cat": "커피", "menu": "", "price": "", "addr": "국회대로66길 11", "bldg": "할렐루야빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1569255197", "name": "메가MGC커피 여의도현대마에스트로점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로66길 11-4", "bldg": "현대마에스트로", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k979551654", "name": "브루다커피 국회의사당역점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로66길 11-4", "bldg": "현대마에스트로", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-chillcoffee", "name": "칠커피바 국회의사당역점", "cat": "커피", "menu": "스페셜티 커피·두쫀쿠", "price": "", "addr": "국회대로66길 11-4 1층 105·106호", "bldg": "현대마에스트로 오피스텔", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k184654527", "name": "매머드익스프레스 여의도산정빌딩점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로66길 23", "bldg": "산정빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k19696736", "name": "스티머스", "cat": "커피", "menu": "", "price": "", "addr": "국회대로66길 23", "bldg": "산정빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-fix", "name": "픽스커피", "cat": "커피", "menu": "저가 아메리카노", "price": "", "addr": "국회대로66길 23 1층 101호", "bldg": "산정빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k574073835", "name": "그레코로스터리카페", "cat": "커피", "menu": "", "price": "", "addr": "국회대로68길 11", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k581976470", "name": "박수진전통찻집", "cat": "차·음료", "menu": "", "price": "", "addr": "국회대로68길 11", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k651425908", "name": "폴바셋 여의도국회대로점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로68길 17", "bldg": "해운빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k26346367", "name": "기다리다", "cat": "커피", "menu": "", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k205919837", "name": "엉클찰스", "cat": "커피", "menu": "", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k754167468", "name": "커프", "cat": "커피", "menu": "", "price": "", "addr": "국회대로68길 23", "bldg": "정원빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1536074398", "name": "곳온니플레이스 웨스트웰리", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 12", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k26532882", "name": "빽다방 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 12", "bldg": "", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-twosome-seo", "name": "투썸플레이스 서여의도점", "cat": "커피", "menu": "케이크·커피", "price": "", "addr": "국회대로70길 15-1 1층", "bldg": "극동VIP빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1821617919", "name": "바나프레소 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 19", "bldg": "대하빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k26974857", "name": "매머드익스프레스 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 22", "bldg": "금강빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k2147373389", "name": "카페쉼", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1801170012", "name": "파르크커피 국회의사당역점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로70길 23", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-droptop", "name": "드롭탑 서여의도점", "cat": "커피", "menu": "아메리카노·에이드", "price": "아메리카노 4.5천", "addr": "국회대로70길 7 1층", "bldg": "동아빌딩", "zone": "alley", "src": "07:00~24:00", "q": "", "franchise": true},
  {"id": "cafe-k290294586", "name": "연호두 국회의사당점", "cat": "베이커리", "menu": "", "price": "", "addr": "국회대로72길 11", "bldg": "프린스텔", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1206538431", "name": "로스터리 락온 국회의사당점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1321840455", "name": "이노스", "cat": "커피", "menu": "", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1544397785", "name": "커피랩케니야", "cat": "커피", "menu": "", "price": "", "addr": "국회대로72길 17", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-mega-seo", "name": "메가MGC커피 서여의도점", "cat": "커피", "menu": "아메리카노", "price": "", "addr": "국회대로72길 17 1층", "bldg": "KCC파크타운", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k573577056", "name": "베이크카페 케니야", "cat": "디저트", "menu": "", "price": "", "addr": "국회대로72길 4", "bldg": "", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-sbux-uisadang", "name": "스타벅스 여의도의사당점", "cat": "커피", "menu": "아메리카노·라떼", "price": "", "addr": "국회대로74길 12", "bldg": "남중빌딩 (켄싱턴호텔 옆)", "zone": "alley", "src": "커피빈과 같은 주소로 검색됨 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-pariscroissant", "name": "파리크라상 여의도2호점", "cat": "베이커리", "menu": "딸기 레어치즈 타르트·케이크", "price": "", "addr": "국회대로74길 12 1층", "bldg": "남중빌딩", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1056061691", "name": "베커라이마리", "cat": "베이커리", "menu": "", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1264774947", "name": "블루샥 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k203961713", "name": "해머스미스커피 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로74길 20", "bldg": "맨하탄21상가", "zone": "alley", "src": "", "q": "", "franchise": true},
  {"id": "cafe-nicecaffeine", "name": "나이스카페인클럽 서여의도점", "cat": "커피", "menu": "쿠키·브라우니·커피", "price": "", "addr": "국회대로74길 20 1층 103-2호", "bldg": "맨하탄21상가", "zone": "alley", "src": "평일 07:30~17:00 · 토 휴무", "q": "", "franchise": true},
  {"id": "cafe-essence", "name": "에센스커피 서여의도점", "cat": "디저트", "menu": "파운드케이크 6종·커피", "price": "쿼터 2.5천 / 홀 1만", "addr": "국회대로74길 20 1층 109호", "bldg": "맨하탄21상가", "zone": "alley", "src": "평일 07:00~17:00 · 주말 휴무 · 카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-k852172875", "name": "씨티커피 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로74길 9", "bldg": "삼보빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k940015301", "name": "네이처셀카페 스템 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로76길 10", "bldg": "기독교침례회총회빌딩", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k323987557", "name": "카페다이얼로그", "cat": "커피", "menu": "", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-k1016401216", "name": "켄싱턴호텔 여의도 더뷰라운지", "cat": "커피", "menu": "", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "", "q": ""},
  {"id": "cafe-timhortons", "name": "팀홀튼 여의도 켄싱턴점", "cat": "디저트", "menu": "도넛·팀빗·커피", "price": "", "addr": "국회대로76길 16", "bldg": "켄싱턴호텔 여의도", "zone": "alley", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-mammoth", "name": "매머드익스프레스 서여의도점", "cat": "커피", "menu": "대용량 아메리카노", "price": "", "addr": "국회대로76길 18 1층 4호", "bldg": "순복음교회 맞은편", "zone": "alley", "src": "평일 07:00~18:00 · 토 휴무", "q": "", "franchise": true},
  {"id": "cafe-coffeebay", "name": "커피베이 여의도순복음교회점", "cat": "커피", "menu": "커피", "price": "", "addr": "국회대로76길 25 1층", "bldg": "여의도순복음교회 앞", "zone": "alley", "src": "커피소녀와 같은 주소로 검색됨 · 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-cbtl-church", "name": "커피빈 여의도순복음교회옆점", "cat": "커피", "menu": "아이스블렌디드·커피", "price": "", "addr": "여의서로 43", "bldg": "한서리버파크 (순복음교회 옆)", "zone": "alley", "src": "1번 출구 760m", "q": "", "franchise": true},
  // ── 국회대로 본선 (LG에클라트·금산빌딩·파라곤)
  {"id": "cafe-baristahee", "name": "바리스타희", "cat": "커피", "menu": "커피", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "cafe-k13018792", "name": "시원재", "cat": "차·음료", "menu": "", "price": "", "addr": "국회대로 750", "bldg": "금산빌딩", "zone": "main", "src": "", "q": ""},
  {"id": "cafe-k1730258822", "name": "더벤티 국회대로점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k792398335", "name": "매머드익스프레스 여의도에클라트점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k2090869227", "name": "우지커피 서여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1193221399", "name": "커피사피엔스 여의도국회대로점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1350722571", "name": "컴포즈커피 국회의사당역점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k454941773", "name": "케이팥", "cat": "디저트", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "cafe-k643188286", "name": "한입원바이트", "cat": "디저트", "menu": "", "price": "", "addr": "국회대로 780", "bldg": "LG여의도에클라트", "zone": "main", "src": "", "q": ""},
  {"id": "cafe-namdaemun", "name": "남대문커피", "cat": "커피", "menu": "아메리카노", "price": "", "addr": "국회대로 780 1층", "bldg": "LG여의도에클라트", "zone": "main", "src": "평일 07:00~20:00", "q": "", "franchise": true},
  {"id": "cafe-sbux-gukhoe", "name": "스타벅스 국회대로점", "cat": "커피", "menu": "아메리카노·프라푸치노", "price": "", "addr": "국회대로 786", "bldg": "", "zone": "main", "src": "1번 출구 도보 4분 · 06:30~20:00", "q": "", "franchise": true},
  {"id": "cafe-k80999414", "name": "볼스 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "국회대로 800", "bldg": "여의도파라곤", "zone": "main", "src": "", "q": ""},
  {"id": "cafe-pascucci", "name": "파스쿠찌 서여의도점", "cat": "커피", "menu": "커피·젤라또·티라미수", "price": "", "addr": "국회대로 800 1층", "bldg": "여의도파라곤", "zone": "main", "src": "평일 08:00~22:00 · 6천 원 이상 2시간 주차", "q": "", "franchise": true},
  // ── 국회의사당역 출구 앞 (익스콘·더샵아일랜드파크)
  {"id": "cafe-k761241088", "name": "에잇비돌체 국회의사당역점", "cat": "디저트", "menu": "", "price": "", "addr": "국회대로 지하 758", "bldg": "국회의사당역 역사 안", "zone": "station", "src": "", "q": ""},
  {"id": "cafe-k927958394", "name": "스몰배치 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 18", "bldg": "", "zone": "station", "src": "", "q": ""},
  {"id": "cafe-k1799405993", "name": "애큐온라운지", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 18", "bldg": "", "zone": "station", "src": "", "q": ""},
  {"id": "cafe-twosome-station", "name": "투썸플레이스 국회의사당역점", "cat": "커피", "menu": "케이크·커피", "price": "", "addr": "의사당대로 21 1층", "bldg": "한국평가데이터", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-ediya", "name": "이디야커피 국회의사당역점", "cat": "커피", "menu": "아메리카노·토피넛라떼", "price": "3.2천~4.5천", "addr": "의사당대로 22 1층", "bldg": "이룸센터 (4번 출구 앞)", "zone": "station", "src": "07:30~20:30", "q": "", "franchise": true},
  {"id": "cafe-pb-kbs", "name": "파리바게뜨 KBS여의도점", "cat": "베이커리", "menu": "케이크·빵", "price": "", "addr": "의사당대로 26", "bldg": "더하우스소호", "zone": "station", "src": "07:00~23:00", "q": "", "franchise": true},
  {"id": "cafe-sbux-kbs", "name": "스타벅스 여의도KBS R점", "cat": "커피", "menu": "아메리카노·라떼", "price": "", "addr": "의사당대로 26 1층 109~113호", "bldg": "더하우스소호", "zone": "station", "src": "월~금 06:30~21:00", "q": "", "franchise": true},
  {"id": "cafe-k134825263", "name": "폴바셋 여의도현대카드점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 3", "bldg": "현대카드 빌딩", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k669599601", "name": "고망고 여의도KBS본점", "cat": "디저트", "menu": "", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1299173034", "name": "매머드익스프레스 여의도KBS본관점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k244044641", "name": "버터커피하우스", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": ""},
  {"id": "cafe-k737639589", "name": "커스텀커피 여의도점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-coffeegirl", "name": "커피소녀", "cat": "커피", "menu": "커피", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "카카오맵 기준 더샵아일랜드파크", "q": ""},
  {"id": "cafe-k1874431010", "name": "클로커피", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 38", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": ""},
  {"id": "cafe-michele", "name": "미켈레커피 여의도점", "cat": "커피", "menu": "에스프레소·라떼", "price": "", "addr": "의사당대로 38 101동 107~108호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "다이닝코드 ★3.8 · 08:00~21:30", "q": "", "franchise": true},
  {"id": "cafe-compose", "name": "컴포즈커피 여의도KBS점", "cat": "커피", "menu": "저가 커피", "price": "", "addr": "의사당대로 38 102동 108호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "카카오 조회에 없음 · 영업 확인 필요", "q": "", "franchise": true},
  {"id": "cafe-sunsun10", "name": "선선10 W여의도점", "cat": "커피", "menu": "커피 (음료 주문 시 러스크 증정)", "price": "", "addr": "의사당대로 38 102동 111호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "07:00~20:00 · 토 10:00~17:00", "q": "", "franchise": true},
  {"id": "cafe-paik", "name": "빽다방 KBS본관점", "cat": "커피", "menu": "원조커피·사라다빵", "price": "", "addr": "의사당대로 38 102동 121호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "매일 07:30~23:00", "q": "", "franchise": true},
  {"id": "cafe-mega", "name": "메가MGC커피 여의도KBS점", "cat": "커피", "menu": "저가 커피·에이드", "price": "", "addr": "의사당대로 38 102동 1층 116호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-gotonly", "name": "곳온니플레이스 여의도점 (PARK SIDE)", "cat": "커피", "menu": "아인슈페너·디저트", "price": "", "addr": "의사당대로 38 103동 107호", "bldg": "더샵아일랜드파크", "zone": "station", "src": "평일 08:00~22:30", "q": ""},
  {"id": "cafe-k1964855917", "name": "스타벅스 국회의사당역점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 8", "bldg": "", "zone": "station", "src": "", "q": "", "franchise": true},
  {"id": "cafe-k1848391861", "name": "어펜딕스 여의도본점", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 8", "bldg": "", "zone": "station", "src": "", "q": ""},
  // ── 국회 경내·KBS
  {"id": "cafe-k24962165", "name": "르뽀미에 여의도KBS점", "cat": "베이커리", "menu": "", "price": "", "addr": "여의공원로 13", "bldg": "KBS", "zone": "west", "src": "", "q": "", "franchise": true},
  {"id": "cafe-bohemian", "name": "보헤미안박이추커피 KBS점", "cat": "커피", "menu": "핸드드립 커피", "price": "", "addr": "여의공원로 13 신관 2층 로비", "bldg": "KBS 신관", "zone": "west", "src": "매일 08:00~20:00", "q": "", "franchise": true},
  {"id": "cafe-k1675199318", "name": "33카페", "cat": "커피", "menu": "", "price": "", "addr": "의사당대로 1", "bldg": "국회 경내", "zone": "west", "src": "", "q": ""},
  {"id": "cafe-dasarang", "name": "다사랑", "cat": "차·음료", "menu": "전통차", "price": "", "addr": "의사당대로 1", "bldg": "국회 의원회관", "zone": "west", "src": "국회 출입 절차 필요", "q": ""},
  {"id": "cafe-k332320982", "name": "파리바게뜨 국회의사당점", "cat": "베이커리", "menu": "", "price": "", "addr": "의사당대로 1", "bldg": "국회 경내", "zone": "west", "src": "", "q": "", "franchise": true},
  {"id": "cafe-heritage815", "name": "헤리티지815카페 국회점", "cat": "커피", "menu": "커피·디저트", "price": "", "addr": "의사당대로 1", "bldg": "국회소통관", "zone": "west", "src": "국회 출입 절차 필요", "q": "", "franchise": true},
  {"id": "cafe-gangbyeon", "name": "강변서재", "cat": "디저트", "menu": "북카페 · 음료·베이커리 (한강뷰)", "price": "", "addr": "의사당대로 1 사랑재 옆 2층", "bldg": "국회 경내", "zone": "west", "src": "일반인 이용 가능 · 다이닝코드 ★4.4 · 평일 08:30~19:00", "q": ""},
];
